apiVersion: apps/v1
kind: Deployment
metadata:
  name: devexercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devexercise
  template:
    metadata:
      labels:
        app: devexercise
    spec:
      containers:
      - name: devexercise
        image: docker.io/mpsoares/devexercise:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: devexercise
spec:
  selector:
    app: devexercise
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      volumes:
      - name: mongodb-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
