name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        #options: >-
        #  --health-cmd "mongosh --eval 'db.adminCommand('ping')'" 
        #  --health-interval 10s
        #  --health-timeout 5s
        #  --health-retries 5


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install -r app/requirements.txt
          pip install requests 

      - name: Run Tests
        run: python -m unittest discover app/tests

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devexercise:${{ github.sha }} ./app
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/devexercise:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/devexercise:latest

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devexercise:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devexercise:latest


